const KANA_ROMAJI: Record<string, string> = {
  あ: "a",
  い: "i",
  う: "u",
  え: "e",
  お: "o",
  か: "ka",
  き: "ki",
  く: "ku",
  け: "ke",
  こ: "ko",
  さ: "sa",
  し: "shi",
  す: "su",
  せ: "se",
  そ: "so",
  た: "ta",
  ち: "chi",
  つ: "tsu",
  て: "te",
  と: "to",
  な: "na",
  に: "ni",
  ぬ: "nu",
  ね: "ne",
  の: "no",
  は: "ha",
  ひ: "hi",
  ふ: "fu",
  へ: "he",
  ほ: "ho",
  ま: "ma",
  み: "mi",
  む: "mu",
  め: "me",
  も: "mo",
  や: "ya",
  ゆ: "yu",
  よ: "yo",
  ら: "ra",
  り: "ri",
  る: "ru",
  れ: "re",
  ろ: "ro",
  わ: "wa",
  を: "wo",
  ん: "n",
  が: "ga",
  ぎ: "gi",
  ぐ: "gu",
  げ: "ge",
  ご: "go",
  ざ: "za",
  じ: "ji",
  ず: "zu",
  ぜ: "ze",
  ぞ: "zo",
  だ: "da",
  ぢ: "ji",
  づ: "zu",
  で: "de",
  ど: "do",
  ば: "ba",
  び: "bi",
  ぶ: "bu",
  べ: "be",
  ぼ: "bo",
  ぱ: "pa",
  ぴ: "pi",
  ぷ: "pu",
  ぺ: "pe",
  ぽ: "po",
  々: "repeat",
};

const SHIKONA_COMPOUND_MEANINGS: Record<string, string> = {
  凌駕: "surpass / excel",
  熱海: "Atami",
  富士: "Fuji / Mt. Fuji",
  平戸: "Hirado",
  御嶽: "Mitake",
  出羽: "Dewa",
  時疾風: "swift time wind",
  風賢央: "wise wind center",
  嘉陽: "auspicious sun",
};

const KANJI_MEANINGS: Record<string, string> = {
  一: "one",
  二: "two",
  三: "three",
  七: "seven",
  八: "eight",
  九: "nine",
  十: "ten",
  千: "thousand",
  万: "ten thousand",
  大: "great",
  小: "small",
  高: "high",
  低: "low",
  若: "young",
  新: "new",
  古: "old",
  荒: "wild",
  正: "proper",
  元: "origin",
  本: "origin",
  意: "intention",
  代: "generation",
  可: "possible",
  不: "not",
  琴: "koto",
  錦: "brocade",
  錬: "forge",
  魁: "pioneer",
  豪: "powerful",
  勢: "force",
  勇: "brave",
  喜: "joy",
  健: "healthy",
  進: "advance",
  動: "move",
  修: "discipline",
  信: "trust",
  輝: "shine",
  翔: "soar",
  飛: "fly",
  昇: "rise",
  勝: "victory",
  優: "excellent",
  栄: "glory",
  盛: "prosper",
  照: "shine",
  光: "light",
  明: "bright",
  晴: "clear sky",
  旺: "flourish",
  煌: "sparkle",
  旭: "rising sun",
  朝: "morning",
  日: "sun",
  月: "moon",
  星: "star",
  天: "heaven",
  空: "sky",
  海: "sea",
  洋: "ocean",
  水: "water",
  波: "wave",
  浪: "wave",
  灘: "open sea",
  瀬: "rapids",
  泉: "spring",
  滝: "waterfall",
  川: "river",
  河: "river",
  湖: "lake",
  港: "harbor",
  津: "haven",
  沢: "marsh",
  沼: "marsh",
  島: "island",
  山: "mountain",
  岳: "peak",
  嶽: "peak",
  富: "wealth",
  士: "warrior",
  峰: "summit",
  岩: "rock",
  石: "stone",
  碇: "anchor",
  砂: "sand",
  里: "village",
  郷: "hometown",
  国: "country",
  田: "rice field",
  野: "field",
  原: "plain",
  地: "earth",
  森: "forest",
  林: "grove",
  木: "tree",
  松: "pine",
  柏: "oak",
  桜: "cherry blossom",
  花: "flower",
  葉: "leaf",
  華: "splendor",
  英: "excellent",
  絢: "brilliant",
  稲: "rice plant",
  菊: "chrysanthemum",
  蘭: "orchid",
  麒: "qilin",
  麟: "qilin",
  龍: "dragon",
  竜: "dragon",
  鳳: "phoenix",
  鵬: "giant bird",
  鷲: "eagle",
  鷹: "hawk",
  鶴: "crane",
  虎: "tiger",
  猿: "monkey",
  馬: "horse",
  駒: "horse",
  兎: "rabbit",
  鹿: "deer",
  熊: "bear",
  狼: "wolf",
  鳥: "bird",
  蛇: "snake",
  鈴: "bell",
  炎: "flame",
  火: "fire",
  風: "wind",
  嵐: "storm",
  雷: "thunder",
  電: "electricity",
  雲: "cloud",
  雪: "snow",
  霧: "mist",
  雨: "rain",
  霜: "frost",
  春: "spring",
  夏: "summer",
  秋: "autumn",
  冬: "winter",
  北: "north",
  南: "south",
  東: "east",
  西: "west",
  中: "middle",
  央: "center",
  上: "upper",
  下: "lower",
  前: "front",
  後: "behind",
  左: "left",
  右: "right",
  安: "peace",
  平: "flat",
  豊: "abundant",
  貴: "noble",
  隆: "prosperous",
  逸: "outstanding",
  遠: "far",
  凌: "surpass",
  駕: "drive",
  藤: "wisteria",
  青: "blue",
  碧: "blue-green",
  翠: "green",
  紅: "crimson",
  白: "white",
  黒: "black",
  赤: "red",
  金: "gold",
  銀: "silver",
  宝: "treasure",
  玉: "jewel",
  王: "king",
  皇: "emperor",
  鉄: "iron",
  剣: "sword",
  力: "strength",
  心: "heart",
  魂: "soul",
  道: "way",
  真: "true",
  清: "pure",
  美: "beauty",
  善: "good",
  寿: "longevity",
  福: "fortune",
  徳: "virtue",
  智: "wisdom",
  聖: "holy",
  義: "justice",
  良: "good",
  尊: "revered",
  雅: "elegance",
  夢: "dream",
  希: "hope",
  志: "aspiration",
  友: "friend",
  佑: "assist",
  悠: "distant",
  牙: "fang",
  阿: "shelter",
  宇: "universe",
  羽: "wing",
  欧: "Europe",
  御: "honorable",
  出: "emerge",
  司: "govern",
  獅: "lion",
  姫: "princess",
  景: "vista",
  戸: "door",
  家: "house",
  間: "space",
  内: "inside",
  関: "barrier",
  熱: "heat",
  栃: "horse chestnut",
  伯: "chief",
  武: "warrior",
  剋: "overcome",
  斧: "axe",
  刃: "blade",
  丸: "round",
  城: "castle",
  崎: "cape",
  岡: "hill",
  坂: "slope",
  宮: "shrine",
  寺: "temple",
  庄: "manor",
  櫻: "cherry blossom",
  湘: "Xiang",
  都: "capital",
  京: "capital",
  佐: "help",
  太: "thick",
  秦: "Qin",
  生: "life",
  目: "eye",
  陽: "sun",
  雄: "hero",
  之: "of",
  結: "bind",
  伊: "that one",
  隠: "hide",
  延: "extend",
  歌: "song",
  潟: "lagoon",
  滑: "slide",
  岐: "branch",
  許: "permit",
  響: "echo",
  向: "facing",
  気: "spirit",
  幸: "happiness",
  甲: "armor",
  行: "go",
  冴: "clear",
  時: "time",
  治: "govern",
  俊: "talented",
  将: "leader",
  尚: "esteem",
  寒: "cold",
  寛: "generous",
  漢: "Han",
  強: "strong",
  興: "rise",
  隈: "corner",
  恵: "blessing",
  軽: "light",
  芸: "art",
  傑: "greatness",
  謙: "modesty",
  醐: "refined",
  口: "mouth",
  孔: "opening",
  広: "wide",
  昂: "rise",
  綱: "rope",
  轟: "roar",
  今: "now",
  児: "child",
  実: "truth",
  狩: "hunt",
  樹: "tree",
  周: "around",
  宗: "sect",
  洲: "sandbar",
  重: "heavy",
  象: "elephant",
  丈: "stature",
  常: "constant",
  須: "must",
  瑞: "auspicious",
  嵩: "lofty",
  成: "become",
  走: "run",
  村: "village",
  多: "many",
  泰: "peaceful",
  醍: "pure",
  谷: "valley",
  淡: "pale",
  禎: "blessing",
  徹: "penetrate",
  登: "climb",
  土: "earth",
  尼: "nun",
  納: "offer",
  畑: "field",
  比: "compare",
  尾: "tail",
  冨: "wealth",
  穂: "ear of grain",
  磨: "polish",
  満: "full",
  名: "name",
  翼: "wing",
  羅: "gauze",
  陸: "land",
  流: "flow",
  諒: "understand",
  緑: "green",
  壽: "longevity",
  惠: "blessing",
  氣: "spirit",
  澤: "marsh",
  濱: "beach",
  號: "name",
  颯: "swift",
  凜: "dignified",
  誠: "sincerity",
  蘇: "revive",
  壮: "robust",
  相: "mutual",
  丹: "red",
  長: "long",
  辻: "crossroads",
  斗: "dipper",
  篤: "sincere",
  斐: "patterned",
  肥: "fertile",
  浜: "beach",
  米: "rice",
  房: "chamber",
  摩: "rub",
  矢: "arrow",
  柳: "willow",
  立: "stand",
  漣: "ripples",
  和: "harmony",
  蔵: "storehouse",
  對: "opposite",
  藪: "thicket",
  藏: "storehouse",
  鳰: "grebe",
  葵: "hollyhock",
  井: "well",
  永: "eternal",
  奄: "cover",
  焔: "flame",
  燕: "swallow",
  艶: "glossy",
  応: "respond",
  屋: "house",
  加: "add",
  幹: "trunk",
  巌: "crag",
  基: "foundation",
  鬼: "demon",
  吉: "luck",
  狗: "dog",
  隅: "corner",
  見: "see",
  玄: "mysterious",
  厚: "thick",
  康: "health",
  鋼: "steel",
  克: "overcome",
  刻: "engrave",
  根: "root",
  阪: "slope",
  薩: "Satsuma",
  讃: "praise",
  室: "room",
  就: "accomplish",
  州: "province",
  住: "dwell",
  駿: "swift horse",
  神: "deity",
  爽: "refreshing",
  総: "whole",
  蒼: "blue",
  速: "fast",
  騨: "dappled horse",
  達: "attain",
  池: "pond",
  筑: "build",
  柱: "pillar",
  跳: "leap",
  塚: "mound",
  庭: "garden",
  典: "code",
  添: "append",
  当: "hit",
  童: "child",
  寅: "tiger sign",
  播: "sow",
  梅: "plum",
  爆: "burst",
  鳩: "dove",
  飯: "meal",
  備: "prepare",
  布: "cloth",
  敷: "spread",
  舞: "dance",
  副: "assist",
  芳: "fragrant",
  柾: "straight grain",
  綿: "cotton",
  揖: "bow",
  藍: "indigo",
  利: "benefit",
  琉: "lapis",
  留: "stay",
  瑠: "lapis",
  令: "command",
  凰: "phoenix",
  國: "country",
  寶: "treasure",
  廣: "wide",
  昴: "Pleiades",
  晟: "bright",
  澁: "astringent",
  猩: "orangutan",
  眞: "true",
  邊: "edge",
  鬨: "war cry",
  黎: "black",
  垣: "fence",
  久: "long time",
  座: "seat",
  子: "child",
  疾: "swift",
  祥: "auspicious",
  人: "person",
  袋: "bag",
  潮: "tide",
  保: "protect",
  望: "hope",
  遥: "distant",
  来: "come",
  麗: "lovely",
  杣: "timber woods",
  渕: "deep pool",
  皓: "white",
  郎: "son",
  乃: "of",
  ノ: "no",
};

export function splitJapaneseName(value: string) {
  return Array.from(value.replace(/\s+/g, ""));
}

export type ShikonaStudyUnit = {
  text: string;
  label: string;
  dictionaryUrl: string;
};

function getDictionaryUrl(value: string, kind: "kanji" | "word") {
  const query = kind === "kanji" ? `${value} #kanji` : value;
  return `https://jisho.org/search/${encodeURIComponent(query)}`;
}

export function getShikonaStudyUnits(value: string): ShikonaStudyUnit[] {
  const characters = splitJapaneseName(value);
  const compounds = Object.keys(SHIKONA_COMPOUND_MEANINGS).sort((a, b) => b.length - a.length);
  const units: ShikonaStudyUnit[] = [];
  let index = 0;

  while (index < characters.length) {
    const remaining = characters.slice(index).join("");
    const compound = compounds.find((entry) => remaining.startsWith(entry));

    if (compound) {
      units.push({
        text: compound,
        label: SHIKONA_COMPOUND_MEANINGS[compound],
        dictionaryUrl: getDictionaryUrl(compound, "word"),
      });
      index += Array.from(compound).length;
      continue;
    }

    const character = characters[index];
    units.push({
      text: character,
      label: getCharacterStudyLabel(character),
      dictionaryUrl: getCharacterDictionaryUrl(character),
    });
    index += 1;
  }

  return units;
}

export function getCharacterStudyLabel(character: string) {
  return KANJI_MEANINGS[character] ?? KANA_ROMAJI[character] ?? "Dictionary";
}

export function getCharacterDictionaryUrl(character: string) {
  return getDictionaryUrl(character, "kanji");
}
